### PR TITLE
Enhanced Heading using Typing Animation

### LINKED ISSUE #153: Enhancing the heading/quote in the page
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
In this current version of the page, the **heading (quote)** is static. This one static quote in the heading makes the first view of the page **less dynamic** as well as unappealing to the users.

- How will this change help?
It will enhance the UI of the webpage. It will ensure users to peek into the main slogans/quotes in the page hence making it more **dynamic** and giving a better user-experience.

#### Description
Please try answering few of those questions
- What changes have to be introduced?
The heading quote **"A place to share your playlists with your friends"** has to be made dynamic where each letters appear one by one and subsequently more quotes are displayed one after the other in an infinite loop. 

- Will this be a breaking change?
No, it will just make the heading quote animated.

- How could it be implemented/designed?
This can be achieved by adding some transitions and animations to the heading (quote) of the page, 
i.e, by adding some more styles/css in the **style.css file** and a pinch of JavaScript in in **index.js file**.

#### Screenshot

pic

### Would be glad if you assign it to me @VG-1

### PR DESCRIPTION
**Pull request by pooranjoyb**
**Description**

- With this enhancement, it will ensure users to peek into the main slogans/quotes in the page eventually giving a better user experience in the page.
- The heading quotes : 
  - "Welcome to PlayListAdda"
  -  "A place to share your playlists with your friends"
  - "Where words fail, music speaks"

  are added, so that they appear in a typing animation.
- Typing.js (A JavaScript typing animation library) is used for working in this issue. 
- The heading-font is also modified to enhance the feel of the animation.

**Related issue(s)**

This PR resolves #153 

**Demo-video**

https://user-images.githubusercontent.com/90945182/196218663-62d9424a-6fde-48ec-ab31-e759a54b29fa.mp4

**Responsiveness**

https://user-images.githubusercontent.com/90945182/196624730-eaf3096e-b8e4-4860-b846-22baaa8dac5d.mp4

### Please add hacktoberfest-accepted label if this PR is merged. @VG-1

### CODE REVIEW

**Comment by VG-1** [comment]
Hey @pooranjoyb thanks for contributing.
I just want to see if it is responsive or not, can you please show it for different screens through a video.
Will be more than happy to merge your pr :)

**Comment by pooranjoyb** [comment]
ok, will get it done by evening! 👍 @VG-1

**Comment by VG-1** [comment]
sure

**Comment by pooranjoyb** [comment]
Demo video for responsiveness is updated in the PR description. 
Would be glad if you check it out Sir. @VG-1

**Comment by VG-1** [comment]
Yeah got it.
Thanks for contributing.
Really appreciate your work :)

**Comment by pooranjoyb** [comment]
@VG-1 Please add hacktoberfest-accepted label to my merge as it was under hacktoberfest2022

**Pull request merged**
