### PR TITLE
Made cards responsive

### LINKED ISSUE #36: Making cards responsive
The website looks a bit clustered on medium and small devices due to 4 cards being in the same row.
Make it responsive

### PR DESCRIPTION
**Pull request by then00bprogrammer**
Made Cards more responsive so that they look better on medium and small screen devices.
* Displaying 3 cards per row for screen size between 1070px and 1368px.
* Displaying 2 cards in a row for screen size between 700px and 1070px.
* Displaying 1 card per row for screen size less than 700px.

Resolves #36

### CODE REVIEW

**Comment by VG-1** [comment]
thanks for working on it.
can you just send some gif or video to it.

**Comment by then00bprogrammer** [comment]
hey @VG-1 please checkout the below video to see if it looks fine
https://www.loom.com/share/1ac70149b5954ab89fac2d48c2179feb

**Review by VG-1 — APPROVED** [review]
Thanks for contributing really appreciate it :)
I will be glad if you can make header and footer responsive too and make another PR.

**Comment by then00bprogrammer** [comment]
Hi @VG-1 
I'll be glad to do that but haven't you assigned a similar issue to another person?
Should I continue working regardless and make another PR? (with or without creating an issue?)
Thank you

**Pull request merged**
