### PR TITLE
Scrollbar customized

### LINKED ISSUE #210: A visually better scroll bar
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
ans: The UI of the project will be hugely affected in a positive way if we make this change.

- How will this change help?
ans:  It will give the user a visually aesthetic experience.

- What is the motivation? 
I am starting out in open Source and want to contribute and hone my skills and this particular feature is best- suited for that. 

#### Description
Please try answering few of those questions

- What changes have to be introduced?
- ans: Scroll bar will be made visually attractive.

- Will this be a breaking change?
ans: No this is a fairly safe change that can be made.

- How could it be implemented/designed?
ans: I can make it using webkit-scrollbar properties in CSS

### PR DESCRIPTION
**Pull request by thisisamandang**
**Description**
This PR refers and resolves #210 , I have used webkit-scrollbar to _modify the scrollbar in the CSS file_ and and have tested this feature and have verified that **it is not a breaking change.**

### CODE REVIEW

**Comment by VG-1** [comment]
Hey @thisisamandang can you share video or gif for the same?

**Comment by thisisamandang** [comment]
Sure, I've Attached a video of the working feature

https://user-images.githubusercontent.com/70525647/197402092-fecf3e77-aeaa-4c2a-a7fa-4a555385eda8.mp4

**Comment by VG-1** [comment]
Great 
I really appreciate it.
Happy Diwali 🪔

**Comment by thisisamandang** [comment]
Happy Diwali 🪔

**Comment by thisisamandang** [comment]
Hey @VG-1 can you add hacktoberfest-accepted label to this PR?

**Pull request merged**
