### PR TITLE
separate js file created

### PR DESCRIPTION
**Pull request by Sammydepoj**
**Description**
separate js file has been created as instructed in the issue.

this pull request resolves issue #30 

- ...
- ...
- ...

**Related issue(s)**

### CODE REVIEW

**Review by VG-1 — COMMENTED** [review]
@Sammydepoj I guess you haven't linked the script.js to index.html

**Review by VG-1 — COMMENTED** [review]
never mind, got it.
just send a screenshot or gif or video of your code working.
will be more than happy to merge it.

**Comment by Sammydepoj** [comment]
Here are the screenshot  of the separate js file and the screenshot of the code working
Capture
Capture11111111111
 You can check them out

**Review by VG-1 — APPROVED** [review]

**Comment by VG-1** [comment]
thanks for contributing @Sammydepoj

**Comment by Sammydepoj** [comment]
My pleasure!

**Pull request closed without merging**
