### PR TITLE
Searchbar/zareenf01

### PR DESCRIPTION
**Pull request by zareenf01**
**Description**

- ...
- ...
- ...

**Related issue(s)**

### CODE REVIEW

**Comment by VG-1** [comment]
Hey can you just add a video or gif for the changes you have made?

**Comment by zareenf01** [comment]
> Hey can you just add a video or gif for the changes you have made?

I have uploaded two files for search bar

**Comment by VG-1** [comment]
@zareenf01 yeah, just wanna see if the code is working fine or not, hence a gif or video.
Will be happy to merge pr after seeing it.

**Comment by zareenf01** [comment]
> @zareenf01 yeah, just wanna see if the code is working fine or not, hence a gif or video. Will be happy to merge pr after seeing it.

https://user-images.githubusercontent.com/109251356/193523218-7f5d28f2-f2b6-4715-8496-2a693cba9963.mp4

**Comment by VG-1** [comment]
Hey @zareenf01 are you able to get playlists after searching their name?
can you just search Should be good and show it?

**Pull request closed without merging**
