### PR TITLE
Favicon Added

### LINKED ISSUE #21: Design a cool logo for the website and add it to title.

### PR DESCRIPTION
**Pull request by impranavtg**
**Description**
Resolves #21, Added a cool favicon for the website.
Ephoto360 com_163412969400dd-removebg-previewnewwwwww

- ...
- ...
- ...

**Related issue(s)**

### CODE REVIEW

**Comment by VG-1** [comment]
Hey @impranavtg can you send a video or gif for the working code.

**Comment by impranavtg** [comment]
https://user-images.githubusercontent.com/83161133/194703877-e8ee45a6-885a-44f4-974a-4e4e566e832a.mp4

**Comment by impranavtg** [comment]
@VG-1 Check this out and please let me know if there is a need for any changes.

**Comment by VG-1** [comment]
thanks for contributing and working on it @impranavtg 
do share it with your friends and help them in making their first PR :)

**Comment by impranavtg** [comment]
Pleasure is mine @VG-1.
Can you assign 'hacktoberfest-accepted' label to this?
It would be really appreciated.

**Pull request merged**
