### PR TITLE
my 1st contribution

### PR DESCRIPTION
**Pull request by nitishmalang**
**Description**

- ...
- ...
- ...

**Related issue(s)**

### CODE REVIEW

**Review by VG-1 — CHANGES_REQUESTED** [review]
hey @nitishmalang glad to see you contributing for the first time.
But kindly add a new spotify playlist link.
thanks

**Comment by nitishmalang** [comment]
> hey @nitishmalang glad to see you contributing for the first time. But kindly add a new spotify playlist link. thanks

okay bro add it in a code base or comment here

**Comment by VG-1** [comment]
add in codebase and commit it again

**Comment by nitishmalang** [comment]
> add in codebase and commit it again

bro I did it you can check it out

**Review by VG-1 — COMMENTED** [review]
Thanks you so much. @nitishmalang 
Can you also change the playlist name in line 378 
and text in line 388.

**Review by VG-1 — COMMENTED** [review]
bro @nitishmalang I wanna merge it, but there is no spotify link now .

**Review by VG-1 — COMMENTED** [review]
bro @nitishmalang I wanna merge it, but there is no spotify link now .

**Comment by nitishmalang** [comment]
> bro @nitishmalang I wanna merge it, but there is no spotify link now .

Screenshot (160)
bro I just checked it out link is there Sharing snapshot with you

**Review by VG-1 — APPROVED** [review]
Got it. 
Congrats on your first contribution.
Hope it hasn't bothered you that much lol

**Comment by nitishmalang** [comment]
thanks bro you helped a lot

**Comment by VG-1** [comment]
No worries.
Do share the project with your friends and help them with their contribution :)

**Pull request merged**
